server:
  port: 8081
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin12345@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.wfj.eureka.consumer.feign.UserFeignClient: DEBUG