server:
  port: 8080
spring:
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin12345@localhost:8761/eureka/
  instance:
    prefer-ip-address: true